# ==========================================
# CYBER LOOK
# TERMINAL COLOR SYSTEM
# ==========================================

background #1a1a2a
foreground #cdd6f4

selection_foreground #1a1a2a
selection_background #4fd6be

url_color #89b4fa


# SYSTEM CORE
color0  #313244
color8  #45475a


# ERROR / ALERT STATE
color1  #f38ba8
color9  #f38ba8


# SUCCESS / SYSTEM SIGNAL
color2  #4fd6be
color10 #4fd6be


# WARNING STATE
color3  #f9e2af
color11 #f9e2af


# INFO LAYER
color4  #89b4fa
color12 #89b4fa


# ACCENT / UI DEPTH
color5  #cba6f7
color13 #cba6f7


# CYBER AURA LAYER
color6  #94e2d5
color14 #94e2d5


# TEXT HIERARCHY
color7  #cdd6f4
color15 #a6adc8
