# ==========================================
# CYBER LOOK 
# SYSTEM CONSOLE LAYER
# ==========================================

# if your wondering 
# this was a fix because bash was starting instead of zsh 
shell /usr/bin/zsh --login
include themes/catppuccin.conf


# ==========================================
# TYPOGRAPHY LAYER (UI TEXT ENGINE)
# ==========================================

font_family JetBrainsMono Nerd Font
font_size 12.5

disable_ligatures never
adjust_line_height 120%
adjust_column_width 0

scrollback_lines 20000


# ==========================================
# WINDOW LAYER (GLASS NODE BEHAVIOR)
# ==========================================

window_padding_width 14

background_opacity 0.85
dynamic_background_opacity yes

hide_window_decorations yes
confirm_os_window_close 0

background_blur 0

sync_to_monitor yes


# ==========================================
# CURSOR LAYER (SYSTEM SIGNAL)
# ==========================================

cursor_shape block
cursor_blink_interval 0.55
cursor_trail 1

cursor #4fd6be


# ==========================================
# TAB SYSTEM (SEGMENTED UI NODES)
# ==========================================

tab_bar_style powerline

active_tab_foreground #1a1a2a
active_tab_background #4fd6be

inactive_tab_foreground #cdd6f4
inactive_tab_background #313244


# ==========================================
# INTERACTION BEHAVIOR (SYSTEM FEEDBACK)
# ==========================================

enable_audio_bell no
visual_bell_duration 0
wheel_scroll_multiplier 1.2

repaint_delay 8
input_delay 3


# ==========================================
# BORDER / PLATFORM INTEGRATION
# ==========================================

wayland_titlebar_color system
macos_titlebar_color system

active_border_color #4fd6be
inactive_border_color #313244
